using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TIKR.Shared.Configuration;

namespace TIKR.Infrastructure.Services;

/// <summary>
/// Writes plaintext secrets to a shared volume file so API + Web both load them at startup
/// (and API refreshes process env immediately after Settings save).
/// </summary>
public interface IRuntimeSecretsStore
{
    string FilePath { get; }
    /// <param name="clearMissing">
    /// When true, missing values clear process env (Settings "clear key").
    /// When false (startup load), leave existing process env alone so host/env keys survive.
    /// </param>
    void ApplyToProcessEnvironment(string? grokApiKey, string? syncfusionLicenseKey, bool clearMissing = false);
    void WriteFile(string? grokApiKey, string? syncfusionLicenseKey);
}

public sealed class RuntimeSecretsStore(IConfiguration configuration, ILogger<RuntimeSecretsStore> logger) : IRuntimeSecretsStore
{
    public string FilePath
    {
        get
        {
            var configured = configuration["TIKR_RUNTIME_SECRETS_PATH"];
            if (!string.IsNullOrWhiteSpace(configured))
                return configured.Trim();

            var dataPath = configuration["TIKR_DATA_PATH"];
            if (!string.IsNullOrWhiteSpace(dataPath))
                return Path.Combine(dataPath.Trim(), "runtime-secrets.env");

            // Docker default volume; local fallback under cwd.
            return Directory.Exists("/data")
                ? "/data/runtime-secrets.env"
                : Path.Combine(Directory.GetCurrentDirectory(), "runtime-secrets.env");
        }
    }

    public void ApplyToProcessEnvironment(
        string? grokApiKey,
        string? syncfusionLicenseKey,
        bool clearMissing = false)
    {
        if (!string.IsNullOrWhiteSpace(grokApiKey))
            Environment.SetEnvironmentVariable("GROK_API_KEY", grokApiKey);
        else if (clearMissing)
            Environment.SetEnvironmentVariable("GROK_API_KEY", null);

        if (!string.IsNullOrWhiteSpace(syncfusionLicenseKey))
            Environment.SetEnvironmentVariable("SYNCFUSION_LICENSE_KEY", syncfusionLicenseKey);
        else if (clearMissing)
            Environment.SetEnvironmentVariable("SYNCFUSION_LICENSE_KEY", null);
    }

    public void WriteFile(string? grokApiKey, string? syncfusionLicenseKey)
    {
        var path = FilePath;
        try
        {
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrWhiteSpace(dir))
                Directory.CreateDirectory(dir);

            var lines = new List<string>
            {
                "# Generated by TIKR Settings — do not commit. Loaded at startup by API and Web.",
            };

            if (!string.IsNullOrWhiteSpace(grokApiKey))
                lines.Add($"GROK_API_KEY={EscapeEnv(grokApiKey)}");
            if (!string.IsNullOrWhiteSpace(syncfusionLicenseKey))
                lines.Add($"SYNCFUSION_LICENSE_KEY={EscapeEnv(syncfusionLicenseKey)}");

            File.WriteAllText(path, string.Join('\n', lines) + "\n");
            logger.LogInformation("Wrote runtime secrets file at {Path}", path);
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Could not write runtime secrets file at {Path}", path);
        }
    }

    private static string EscapeEnv(string value)
    {
        if (value.Contains('"') || value.Contains(' ') || value.Contains('#'))
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        return value;
    }
}

public static class RuntimeSecretsEnvLoader
{
    /// <summary>Load shared runtime-secrets.env without clobbering existing process env.</summary>
    public static void LoadIfExists(IConfiguration configuration)
    {
        var path = configuration["TIKR_RUNTIME_SECRETS_PATH"];
        if (string.IsNullOrWhiteSpace(path))
        {
            var dataPath = configuration["TIKR_DATA_PATH"];
            path = !string.IsNullOrWhiteSpace(dataPath)
                ? Path.Combine(dataPath.Trim(), "runtime-secrets.env")
                : Directory.Exists("/data")
                    ? "/data/runtime-secrets.env"
                    : null;
        }

        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            return;

        DotNetEnv.Env.Load(path, DotNetEnv.LoadOptions.NoClobber());
    }
}
