<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\TIKR.Shared\TIKR.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Helpers\Fixtures\email\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
