<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TIKR.SyncfusionDocuments</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TIKR.Shared\TIKR.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.1" />
    <PackageReference Include="Syncfusion.DocIO.Net.Core" Version="33.2.15" />
    <PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="33.2.15" />
    <PackageReference Include="Syncfusion.Licensing" Version="33.2.15" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="33.2.15" />
    <PackageReference Include="Syncfusion.XlsIO.Net.Core" Version="33.2.15" />
    <PackageReference Include="Syncfusion.XlsIORenderer.Net.Core" Version="33.2.15" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TIKR.Infrastructure.Tests" />
  </ItemGroup>

</Project>